[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "application/javascript"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Resource-Policy = "cross-origin"
    Cross-Origin-Isolation = "enable-cross-origin-isolation"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Resource-Policy = "cross-origin"
    Cross-Origin-Isolation = "enable-cross-origin-isolation"
    Cache-Control = "public, max-age=31536000, immutable"

